name: glytch25
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.13
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - addict==2.4.0
      - affine==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - anywidget==0.9.21
      - appdirs==1.4.4
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bcrypt==5.0.0
      - blinker==1.9.0
      - boto3==1.42.4
      - botocore==1.42.4
      - bqplot==0.12.45
      - branca==0.8.2
      - brotli==1.2.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - comm==0.2.3
      - configilm==0.7.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - defusedxml==0.7.1
      - earthengine-api==1.7.3
      - eerepr==0.1.2
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastapi==0.121.2
      - ffmpy==1.0.0
      - filelock==3.19.1
      - filetype==1.2.0
      - fiona==1.10.1
      - fire==0.7.1
      - flask==3.1.2
      - flask-bcrypt==1.0.1
      - flask-cors==6.0.1
      - flask-login==0.6.3
      - flask-sqlalchemy==3.1.1
      - flask-wtf==1.2.2
      - flatbuffers==25.9.23
      - folium==0.20.0
      - fonttools==4.61.0
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - future==1.0.0
      - geedim==1.9.1
      - geemap==0.36.6
      - geocoder==1.38.1
      - geopandas==1.1.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.43.0
      - google-auth-httplib2==0.2.1
      - google-cloud-core==2.5.0
      - google-cloud-storage==3.6.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - gradio==6.0.2
      - gradio-client==2.0.1
      - greenlet==3.3.0
      - groovy==0.1.2
      - groundingdino-py==0.4.0
      - grpcio==1.76.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.7
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - ipyevents==2.0.4
      - ipyfilechooser==0.6.0
      - ipyleaflet==0.20.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.2
      - jupyter-leaflet==0.20.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lazy-loader==0.4
      - lightning==2.5.6
      - lightning-utilities==0.15.2
      - lmdb==1.7.5
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - multidict==6.7.0
      - narwhals==2.13.0
      - networkx==3.3
      - numpy==1.26.4
      - omegaconf==2.3.0
      - onnx==1.20.0
      - onnxruntime-gpu==1.23.2
      - open-clip-torch==3.2.0
      - opencv-contrib-python==4.12.0.88
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.10.0.84
      - orjson==3.11.5
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pi-heif==1.1.1
      - pillow==11.3.0
      - pillow-avif-plugin==1.5.2
      - platformdirs==4.5.1
      - plotly==6.5.0
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.2
      - psutil==7.1.3
      - psygnal==0.15.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybboxes==0.1.6
      - pycocotools==2.0.10
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pyogrio==0.12.1
      - pyparsing==3.2.5
      - pyperclip==1.11.0
      - pyproj==3.7.1
      - pyreadline3==3.5.4
      - pyshp==3.0.3
      - python-box==7.3.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-magic-bin==0.4.14
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.6
      - pytorchwildlife==1.2.4.2
      - pytz==2025.2
      - pyyaml==6.0.3
      - rasterio==1.4.3
      - ratelim==0.1.6
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - roboflow==1.2.11
      - rsa==4.9.1
      - rtree==1.4.1
      - s3transfer==0.16.0
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - sahi==0.11.36
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - scooby==0.11.0
      - seaborn==0.13.2
      - segmentation-models-pytorch==0.5.0
      - semantic-version==2.10.0
      - shapely==2.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sqlalchemy==2.0.44
      - stack-data==0.6.3
      - starlette==0.49.3
      - supervision==0.6.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - terminaltables==3.1.10
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.22
      - tokenizers==0.22.1
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchmetrics==1.8.2
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - traitlets==5.14.3
      - traittypes==0.2.3
      - transformers==4.57.1
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ultralytics==8.3.235
      - ultralytics-thop==2.0.18
      - uritemplate==4.2.0
      - urllib3==2.6.0
      - uvicorn==0.38.0
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - websockets==15.0.1
      - werkzeug==3.1.4
      - wget==3.2
      - widgetsnbextension==4.0.15
      - wtforms==3.2.1
      - xyzservices==2025.11.0
      - yapf==0.43.0
      - yarl==1.22.0
      - yolov5==7.0.13
      - yt-dlp==2025.11.12
prefix: C:\Users\Santhosh V\.conda\envs\glytch25
